name: Fetch ZIP and Compute Hash

on:
  workflow_dispatch:

jobs:
  fetch_and_hash:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch ZIP file with retry
        run: |
          curl -L --retry 5 --retry-delay 5 --max-time 300 \
            -A "Mozilla/5.0" \
            "https://easyradiology.aversiclinic.ge/eri/e391wodf-a8ibjzhp-2uzhl2d3-idaalpek.zip" -o file.zip

      - name: Compute SHA-256 hash
        run: |
          sha256sum file.zip > hash.txt
          echo "Computed SHA-256 hash:"
          cat hash.txt

      - name: Upload hash artifact
        uses: actions/upload-artifact@v4
        with:
          name: zip-hash
          path: hash.txt
